### ISSUE TITLE
Multiple ScrollController [Feature]

### ISSUE THREAD

**Issue by tusharbhambere** [insolite-dev/hidable#20]
Use-case 
Hidable Using on Bottom Navigation 4 Page Have their Separate ScrollController
 If We make pass same ScrollController then Error Come out -ScrollController attached to multiple scroll views.

**Comment by theiskaa** [comment]
Hi! @tusharbhambere thanks for interest.


What about wrapping all screens with one scrollable widget and passing scroll controller to that widget? Like we have in example.

I'm proposing this for only mean-time solution, gonna think about the issue and inform you soon. 

Thank you.

**Comment by tusharbhambere** [comment]
wrapping all screens with one scrollable widget -
In this case somePage have ListView Widget Some Page have Custom ScrollView Widget or Some page have their our Logic of scrolling then?
Its Good Code Practise?

Thank You for Reply..!

**Comment by theiskaa** [comment]
No, I just proposed a possible solution for now, not a perfect one.

**Comment by theiskaa** [comment]
@tusharbhambere According to Flutter documentation:
> In Flutter, a ScrollController can only be attached to a single scrollable widget at a time. If you try to attach the same ScrollController to multiple scrollable widgets, it will throw an error because it can't manage the scroll position of multiple widgets simultaneously.

So, in your case you probably gonna need to put a different scroll controller for each section.
Or maybe for each page have a List of Widget(s) and use them inside one scroll controller.

<details><summary>Example</summary>
<p>

```dart
class _ExampleState extends State<Example> {
  final colorsPath = [Colors.green, Colors.orangeAccent, Colors.orange, Colors.red];

  int index = 0;

  // Create a single scroll controller
  final ScrollController scrollController = ScrollController();

  // Create a list of widgets for each page
  final List<Widget> pages = [
    Page1(),
    Page2(),
    Page3(),
    Page4(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: Hidable(
        controller: scrollController, // Use the single controller
        child: AppBar(
          backgroundColor: colorsPath[index].withOpacity(.6),
          title: const Text('Hidable'),
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 10),
        child: ListView(
          controller: scrollController, // Use the single controller
          children: [pages[index]], // Display the widget for the current page
        ),
      ),
      bottomNavigationBar: Hidable(
        controller: scrollController, // Use the single controller
        enableOpacityAnimation: true,
        child: BottomNavigationBar(
          currentIndex: index,
          onTap: (i) => setState(() => index = i),
          items: bottomBarItems(),
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      floatingActionButton: Hidable(
        controller: scrollController, // Use the single controller
        child: Align(
          alignment: Alignment.centerRight,
          child: FloatingActionButton(
            child: const Icon(Icons.label),
            backgroundColor: colorsPath[index].withOpacity(.8),
            onPressed: () {},
          ),
        ),
      ),
    );
  }

  // ... rest of your code ...
}
```

</p>
</details>

I'm closing the issue because there's nothing much we can do as i see, only solution could be as i mentioned changing the approach of implementation. Thanks again.
If you think we're mistaken, please feel free to reopen the issue.
