### ISSUE TITLE
Add option to reveal hidden widget while scrolling back

### ISSUE THREAD

**Issue by radibobovich** [insolite-dev/hidable#26]
I tried to use the widget on AppBar to implement a common behavior, when the appbar hides when you scroll down, and shows again when you scroll up. But as I can see widget reveal triggers only when you are close to zero scroll offset. It would be nice to have an option when revealing also triggers while scrolling back.

**Comment by radibobovich** [comment]
@theiskaa 
I'm attaching wanted behavior compared to your widget behavior

<img src="https://github.com/insolite-dev/hidable/assets/80050269/7a8ff043-511e-48ce-a818-4abd3e3ac993" width="200"/>
<img src="https://github.com/insolite-dev/hidable/assets/80050269/27ddc4e8-cc4a-4d1f-814f-20605ae1a5ff" width="200"/>

**Comment by theiskaa** [comment]
So .. you want to an option to customise the scrolling visibility algorithm? Am I right?

**Comment by theiskaa** [comment]
If, so. I'll implement asap and assign you as reviewer. @radibobovich

**Comment by radibobovich** [comment]
> So .. you want to an option to customise the scrolling visibility algorithm? Am I right?

That's right, thank you for quick response! Would love to review it once you get it done.

**Comment by theiskaa** [comment]
@radibobovich good evening/morning, I'm finished implementation, and let's see if we understood each other correctly. I'll write example implementation, in the PR itself -> #27.

**Comment by theiskaa** [comment]
@radibobovich I'll wait for your comment of approval, and then merge to develop.

**Comment by radibobovich** [comment]
Hey @theiskaa, I checked the feature and made use of it, thank you. This is the function I passed to the widget to implement the desired behavior:
```dart
double customHidableVisibility(ScrollPosition position, double previousOffset,
    double currentOffset, double currentVisibility) {
  const double deltaFactor = 0.08;

  /// When user scrolls down
  if (position.userScrollDirection == ScrollDirection.reverse) {
    return (currentVisibility - deltaFactor).clamp(0, 1);
  }

  /// When user scrolls up
  if (position.userScrollDirection == ScrollDirection.forward) {
    return (currentVisibility + deltaFactor).clamp(0, 1);
  }
  return currentVisibility;
}
```
 I also checked the code you provided in your first reply more carefully:

> ```dart
> /// We set visibility to zero (which probably could be optional, able to customize from widget)
> if (position.axisDirection == AxisDirection.down && position.extentAfter == 0.0) {
>   if (visibilityNotifier.value == 0.0) return;
>   visibilityNotifier.value = 0.0;
>   return;
> }
> 
> /// We set visibility to one (which probably could be optional, able to customize from widget)
> if (position.axisDirection == AxisDirection.up && position.extentBefore == 0.0) {
>   if (visibilityNotifier.value == 1.0) return;
>   visibilityNotifier.value = 1.0;
>   return;
> }
> ```
And I found out that the last condition probably doesn't work as intended (it is never true), because `position.axisDirection` doesn't represent the direction user scrolls in (check it [here](https://groups.google.com/g/flutter-dev/c/h-X9UkSAls4)), so it will always say `AxisDirection.down`, you probably want to use `position.userScrollDirection` instead.

Also, while I was trying to implement the "reveal-on-scroll-back" feature, I was confused by the `previousOffset` because it actually represents the offset only while scroll offset is less than `preferredSize`, then it just clamps to it. Looks like intended though, but I couldn't make use of it while implementing back scroll revealing logic and thus used naive substraction instead.

**Comment by theiskaa** [comment]
I'm happy to hear that!

regarding the original algorithm, not sure actually. I'll test and let you know. I loved your customised implementation, much simpler than ours. Also will think about replacement, since it will make no difference, after making it able to customise the algorithm itself.
Thanks again!

**Comment by theiskaa** [comment]
I finally got time to test and clear up things.
I really appreciate your suggestions, and yeah we're at here. I replaced the algorithm with yours, now it has default implementation like that, plus I've provided the extra deltaFactor field to Hidable widget itself. So you can decide the strength of functioning without re-writing the algorithm itself.
Tho, I also removed some unused fields and variables from controller, I've removed the size, current/previous offsets from the HidableVisibility function type and also from controller. We don't need 'em.

I'll merge now, If you think that suits your needs well.
Check the PR, for updated example.
