### ISSUE TITLE
More than one Hidable widget on the same screen

### ISSUE THREAD

**Issue by MobiNeil** [insolite-dev/hidable#9]
My page design calls for two widgets which need hiding when the list is scrolled, one at the top and one at the bottom. If I create two Hidable widgets in one class, it doesn't seem possible to set the size correctly.  Whatever size value I give the top Hidable, it seems to apply this also to the bottom one, regardless of the value I set there.

Is there a workaround for this, or any suggestion as to how I might implement this?

**Comment by theiskaa** [comment]
Hello! thanks for reporting the problem.
But, can you be more clear about visual and your code? It would be definitely great to see the final "non-work" result and the code.

**Comment by JarikH** [comment]
@theiskaa I'm having the same issue, where when i wrap my AppBar and my BottomNavigationBar with Hidable, my bottomnavigation bar is giving me errors that the widget is overflowing by 2 pixels on the bottom, and when i remove it from the top bar this dissapears, also the height of my AppBar is completely broken when i wrap it with hidable
Code with issues
` appBar: Hidable(
        controller: scrollController,
        child: AppBar(
          title: Text('Startpagina'),
        )
),`
`
      bottomNavigationBar: Hidable(
        preferredWidgetSize: Size.fromHeight(58),
        child: BottomNavigationBar(
          currentIndex: _selectedIndex,
          onTap: _onItemTapped,
          selectedItemColor: Colors.black,
          unselectedItemColor: Colors.black,
          items: [
            BottomNavigationBarItem(
              icon: Icon(Icons.home_outlined),
              activeIcon: Container(
                  decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.secondaryContainer,
                      shape: BoxShape.rectangle,
                      borderRadius: BorderRadius.all(Radius.circular(25.0))),
                  width: 70.0,
                  child: Icon(Icons.home)),
              label: 'Startpagina',
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.person_outline),
              activeIcon: Container(
                  decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.secondaryContainer,
                      shape: BoxShape.rectangle,
                      borderRadius: BorderRadius.all(Radius.circular(25.0))),
                  width: 70.0,
                  child: Icon(Icons.person)),
              label: 'Mijn',
            )
          ],
      ),
      controller: scrollController)`
      
      And it works when i just fine
      
      Image while wrapping both options in hidable:
![Screenshot_20221130-085945](https://user-images.githubusercontent.com/10828636/204741207-1c918a20-2d12-4167-affd-a4f0b1fef5ff.png)
When i remove the hidable the appbar returns to normal size and the bottomnavigationbar is no longer overflowed

**Comment by JarikH** [comment]
```
import 'package:flutter/material.dart';
import 'package:holybot/interfaces/activity.dart';
import 'package:holybot/l10n/l10n.dart';
import 'package:holybot/repository.dart';
import 'package:provider/provider.dart';
import 'package:holybot/globals.dart' as globals;
import 'package:hidable/hidable.dart';

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  int _selectedIndex = 0;
  late Stream<List<Activity>>? _activityStream;
  final ScrollController scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    _activityStream = context.read<Repository>().getActivities(globals.orgId!);
  }

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    return Scaffold(
      appBar: Hidable(
        controller: scrollController,
        child: AppBar(
          title: Text('Startpagina'),
          // centerTitle: true,
        )
      ),
      bottomNavigationBar: Hidable(child: BottomNavigationBar(
        currentIndex: _selectedIndex,
        onTap: _onItemTapped,
        selectedItemColor: Colors.black,
        unselectedItemColor: Colors.black,
        items: [
          BottomNavigationBarItem(
            icon: Icon(Icons.home_outlined),
            activeIcon: Container(
                decoration: BoxDecoration(
                    color: Theme.of(context).colorScheme.secondaryContainer,
                    shape: BoxShape.rectangle,
                    borderRadius: BorderRadius.all(Radius.circular(25.0))),
                width: 70.0,
                child: Icon(Icons.home)),
            label: 'Startpagina',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person_outline),
            activeIcon: Container(
                decoration: BoxDecoration(
                    color: Theme.of(context).colorScheme.secondaryContainer,
                    shape: BoxShape.rectangle,
                    borderRadius: BorderRadius.all(Radius.circular(25.0))),
                width: 70.0,
                child: Icon(Icons.person)),
            label: 'Mijn',
          )
        ],
      ), controller: scrollController),
    );
  }

  StreamBuilder<List<Activity>> activitiesList(AppLocalizations l10n) {
    return StreamBuilder<List<Activity>>(
      stream: _activityStream,
      builder: (BuildContext context, AsyncSnapshot<List<Activity>> snapshot) {
        if (snapshot.hasError) return Text('Error: ${snapshot.error}');
        switch (snapshot.connectionState) {
          case ConnectionState.waiting:
            return Text(l10n.homeActivitiesLoading);
          default:
            if (snapshot.data?.length == 0) {
              return Expanded(
                child: SizedBox(
                  height: 200.0,
                  child: Image.asset(
                    'assets/images/no_activities.png',
                  ),
                ),
              );
            }
            return Expanded(
              child: SizedBox(
                height: 200.0,
                child: ListView(
                  controller: scrollController,
                  scrollDirection: Axis.vertical,
                  children: snapshot.data?.map((Activity activity) {
                    return Padding(
                      padding: const EdgeInsets.only(
                          left: 20.0, right: 20.0, bottom: 20.0),
                      child: Card(
                          child: Column(
                        children: [
                          getImage(activity),
                          ListTile(
                            title: Text(activity.name),
                            trailing: Icon(Icons.bookmark_border),
                            subtitle: Text(
                                'Hier moet dus een secundaire tekst komen uit een activity'),
                            isThreeLine: true,
                          ),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Padding(
                                padding: const EdgeInsets.only(
                                    left: 10.0, bottom: 10.0),
                                child: Container(
                                  child: Row(
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    children: [
                                      Icon(Icons.location_on_outlined),
                                      Text('Nijmegen')
                                    ],
                                  ),
                                ),
                              ),
                              Padding(
                                padding: const EdgeInsets.only(
                                    right: 20.0, bottom: 10.0),
                                child: Container(
                                  child: Row(
                                    mainAxisAlignment: MainAxisAlignment.end,
                                    children: [
                                      Icon(Icons.check_circle,
                                          color: Theme.of(context)
                                              .colorScheme
                                              .primary),
                                      Text('VvSB activiteit')
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          )
                        ],
                      )),
                    );
                  }).toList() as List<Widget>,
                ),
              ),
            );
        }
      },
    );
  }

  Image getImage(Activity activity) {
    String imageUrl = activity.image ?? 'assets/images/no_activities.png';
    return Image.asset(
      imageUrl,
      width: 300.0,
      height: 200.0,
    );
  }

  String getInitial(String name) {
    List<String> list = name.split("");
    return list.first;
  }

  void _onItemTapped(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }
}
```

This is the statefull widget

**Comment by JarikH** [comment]
Ooh I've also figured out that the Bottom overflowed by 2.0 pixels only happens when useMateria3: true, is on in in the ThemeData. But the Appbar still becomes really small when i also wrap it with the hidable widget

**Comment by theiskaa** [comment]
I personally use `hidable` in my private and public projects, and also the example implements the` Hidable` widget for `AppBar`, `BottomNavigationBar`, and even for `FloatingActionButton`. But I didn't recognize any any kinda issue while using it.
It would be definitely another code factor that directly affects the context(main) styles of widgets that forces hidable to be small in `AppBar`
As you mentioned before, `ButtonNavigationBar` were craching cuz of `ThemeData`, probably kinda similar thing is happening for the `AppBar` also.

**Comment by theiskaa** [comment]
I've to close this issue right now because there is no issue directly in the `Hidable` widget that could be handled by testing it normally.

@JarikH, @MobiNeil if you find an exact case where this happens, and you thing it could be fixed by improving the `Hidable` widget itself, please re-open this issue or create a nother one with exact content.

**Thanks for your time and contribution to the package you guys made ❤️**
